version: '3.2'
services:
  lizmap:
    image: gsalin/docker-lizmap-pg:3.1.12
    restart: on-failure
    ports:
     - 80:80
     - 443:443
    env_file:
      - ./database.env
    volumes:
     - project:/home
     - var:/var/www/websig/lizmap/var
    depends_on:
      - postgis
      - qgiserver
    links:
     - qgiserver:qgiserver
     - postgis:postgis
     
  qgiserver:
    image: kartoza/qgis-server:LTR
    hostname: qgiserver
    volumes:
      # Wherever you want to mount your data from
      - project:/home
    ports:
      - 8080:80
    expose:
      - 8080
    env_file:
      - ./database.env

  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    expose:
      - 5432

    entrypoint: >
      bash -c "wget -N -P / https://github.com/2p2r/docker-lizmap/raw/master/docker-postgis/setup-database.sh &&
               /docker-entrypoint.sh"
    env_file:
      - ./database.env
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0    

    volumes:
      - postgres:/var/lib/postgresql
      
  pgadmin4:
    image: chorss/docker-pgadmin4
    restart: on-failure
    ports:
      - 5050:5050
    volumes:
      - pgadmin4:/data
     
volumes:
   pgadmin4:
   postgres:
   var:
   project: